# Application URLs
url_base=https://opensource-demo.orangehrmlive.com/

# Browser Configuration
browser=chrome

# Credentials
username=orangehrm_hverma
password=Passw0rd@7654321

# Wait Configuration
implicitWait=10
explicitWait=10
